language: csharp
dist: trusty
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
sudo: required
mono: none
dotnet: 1.0.1
os:
  - linux
script:
  - dotnet restore
  - dotnet build NUsecase.sln -c Release -f netcoreapp1.1
  - dotnet test NUsecase.Tests/NUsecase.Tests.csproj -c Release -f netcoreapp1.1
