language: csharp
solution: NUsecase.sln

matrix:
  include:
  - os: linux
    dist: xenial
    dotnet: 1.0.1
    mono: none
    env: DOTNETCORE=1
    sudo: required

install:
  - sudo apt-get install -y nuget
  - nuget restore NUsecase.sln
  - nuget install NUnit.Runners -Version 3.5.0 -OutputDirectory testrunner
  
script:
  - xbuild /p:Configuration=Release NUsecase.sln
